#!/bin/bash
sudo su
yum update -y
yum install httpd -y
cd /var/www/html
echo "524">index.html
service httpd start
chkconfig httpd on



[ec2-user@ip-10-0-0-57 ~]$ cat /var/www/html/index.html
532
[ec2-user@ip-10-0-0-57 ~]$ echo "524" | sudo tee /var/www/html/index.html
524
[ec2-user@ip-10-0-0-57 ~]$ cat /var/www/html/index.html
524

